version: "3.9"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - devnet
    tty: true
    stdin_open: true
    ports:
      - 5000:5000

networks:
  devnet: {}
